language: zh-CN
intents:
  HassGetCurrentTime:
    data:
      - sentences:
          - "现在什么时间"
          - "现在是什么时间"
          - "现在的时间是什么"
          - "请问现在什么时间"
          - "请问现在是什么时间"
          - "现在几点"
          - "现在几点了"
          - "现在是几点"
          - "现在几点钟"
          - "请问现在几点"
        response: default
